CREATE TABLE db_bestblogs.Comment (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    PostId CHAR(36) NOT NULL,
    Content TEXT NOT NULL,
    Author VARCHAR(255) NOT NULL,
    CreationDate DATETIME NOT NULL,
    UpdateDate DATETIME DEFAULT NULL,
    CONSTRAINT FK_Post FOREIGN KEY (PostId) REFERENCES Post(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
