#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Copy migrations from src folder
COPY ./Migrations/ ./Migrations/
WORKDIR /src/Migrations
RUN dotnet publish -c Release -o /app /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "Migrations.dll"]