# This file must be run with environment file test-env
# e.g.
# $ docker compose up -d --build
# $ docker compose down
services:
  bestblogs-api:
    image: bestblogs-api:latest
    container_name: bestblogs-webapi
    build:
      context: .
      dockerfile: Api/DockerFile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8080:8080"
    networks:
      - net
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      CONNECTIONSTRINGS__DB_BESTBLOGS: >-
        server=bestblogs-mysql;
        database=db_bestblogs;
        user=root;
        password=rootpw;
        Persist Security Info=False;
        CharSet=utf8;
        Allow User Variables=True
      USE_IN_MEMORY_DB: "false"
    depends_on:
      - bestblogs-migrations
      
  bestblogs-mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - net
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
    # files available in the sql folder will be run on mysql init -> db dump.sql for local
      - ./sql:/docker-entrypoint-initdb.d
      
  bestblogs-migrations:
    image: db-migrations:latest
    build:
      context: .
      dockerfile: Migrations/DockerFile
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Local
      CONNECTIONSTRINGS__DB_BESTBLOGS: >-
        server=bestblogs-mysql;
        database=db_bestblogs;
        user=root;
        password=rootpw;
        Persist Security Info=False;
        CharSet=utf8;
        Allow User Variables=True
    depends_on:
      - bestblogs-mysql
    command: 'dotnet Migrations.dll'
    networks:
      - net
networks:
  net:

